<a href="https://colab.research.google.com/github/cotozelo/Data_Science_Machine_Learning_-_Data_ICMC/blob/main/Notebooks/Aula_01/Aula_01_Python_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercícios Python e Numpy


## Python

Aqui na parte de Python vamos passar por algumas das principais coisas que você precisa saber, é claro que não colocamos tudo de importante da linguagem, só o mais necessário.

### Variáveis

In [25]:
# Declare uma variavel chamada a e atribua o valor 10 a ela
a = 10

In [26]:
# Imprime essa variavel que você acabou de criar
print(a)

10


In [27]:
# Crie uma outra variavel b que recebe o valor de a so que como string
b = str(a)

In [28]:
# Combine sua variavel b a variavel abaixo para obter a string "Hello 10" em uma variavel d
c = "Hello "
d = f'{c} {b}'

In [29]:
# Imprima a variável d
print(d)

Hello  10


### Strings

In [30]:
my_str = 'Insira uma frase aqui!'

In [31]:
# Substitua a exclamação da frase por uma interrogação
# (Dica: A funcão altera inplace ou retorna uma copia modificada?)
my_str = my_str.replace('!', '?')
my_str

'Insira uma frase aqui?'

In [32]:
# Crie uma lista "my_words" com cada palavra a frase
my_words = my_str.split()
my_words

['Insira', 'uma', 'frase', 'aqui?']

### Listas

In [33]:
lista = [1, 23, 31, 40, 56, 16]

In [34]:
# Faça um for que imprima cada elemento da lista "lista" (Lembre-se que o for em python é um for each)
for elemento in lista: print(elemento)

1
23
31
40
56
16


In [35]:
# Faça um for que imprima o dobro de cada elemento da lista "lista" 
for elemento in lista: print(elemento*2)

2
46
62
80
112
32


In [36]:
# Gere uma lista chamada "dobro" com o dobro de cada elemento de "lista" usando list comprehension
dobro = [elemento*2 for elemento in lista]
dobro

[2, 46, 62, 80, 112, 32]

In [37]:
# Crie uma nova lista chamada "pares"
# Faça um for que itetere sobre a lista "lista" e para cada elemento impar coloque ele no fim da lista "pares"
# Imprima a lista "pares"
pares = []
for elemento in lista:
    if elemento % 2 == 0:
        pares.append(elemento)
        
pares    

[40, 56, 16]

In [38]:
lista2 = ['oi', 2, 2.5, 'top', 'python', 45]

In [39]:
# Faça um for pela "lista2" e imprima todos os elementos que são strings (Dica: pesquise pela função type())
for elemento in lista2:
    if isinstance(elemento, str):
        print(elemento)

oi
top
python


#### Indexando

In [40]:
my_list = [0, 10, 20, 30, 40, 50, 60, 70]

In [41]:
# Selecione o ultimo elemento da lista
my_list[-1]

70

In [42]:
# Selecione do primeiro até o 4 elemento da lista
my_list[:4]

[0, 10, 20, 30]

In [43]:
# Selecione do segundo elemento da lista até o quinto
my_list[1:5]

[10, 20, 30, 40]

In [44]:
# Selecione do primeiro elemento da lista até o penultimo
my_list[0:-1]

[0, 10, 20, 30, 40, 50, 60]

### Dicionários

In [45]:
lista = ['a', 'a', 'b', 'a', 'c', 'd', 'e', 'b', 'b', 'c']

In [46]:
# Crie um dicionario que contenha a contagem de cada elemento do vetor
from collections import Counter
my_dict = dict(Counter(lista))
my_dict

{'a': 3, 'b': 3, 'c': 2, 'd': 1, 'e': 1}

In [47]:
print(my_dict)

{'a': 3, 'b': 3, 'c': 2, 'd': 1, 'e': 1}


### Funções

In [48]:
# Crie uma função soma_elementos() que recebe uma lista e retorna a soma de todos os seus elementos
def soma_elementos(lista):
    return sum(lista)

In [49]:
soma_elementos([1, 2, 3, 4, 5])

15

In [50]:
soma_elementos([-1, 5, 7, -2])

9

In [51]:
# Crie uma função produto_escalar() que recebe duas listas de tamanho igual e calcula o produto escalar entre elas
# Dica: Utilize a função zip
def produto_escalar(lista1, lista2):
    produto = []
    for ele1, ele2 in zip(lista1, lista2):
        produto.append(ele1 * ele2)
    return produto

In [52]:
produto_escalar([1, 2, 3], [0, 4, 7])

[0, 8, 21]

In [53]:
produto_escalar([10, 20, 40, 1], [23, 4, 2, 1])

[230, 80, 80, 1]

In [54]:
# Crie uma função par_ou_impar() que recebe um numero n é para cada numero de 1 a n imprime o numero
# seguido de par ou impar, dependendo do que ele seja. Caso o usuário não coloque nada n deve valer 20
# Exemplo: par_ou_impar(4)
#   1 Impar
#   2 Par
#   3 Impar
#   4 Par
def par_ou_impar(n=20):
    if n % 2 == 0:
        print(f'{n} Par')
    else:
        print(f'{n} Impar')

In [55]:
par_ou_impar(15)

15 Impar


In [56]:
par_ou_impar(15)

15 Impar


In [57]:
# Crie uma função diga_indice() que recebe uma lista e imprime o indice de cada elemento e em seguida 
# o proprio elemento
# Exemplo: diga_indice(['oi', 'tudo', 'bem'])
#    0 oi
#    1 tudo
#    2 bem
# (DICA: Pesquise pela função enumerate)
def diga_indice(lista):
    for k, v in enumerate(lista):
        print(f'{k} {v}')

In [58]:
diga_indice(['1', '2', '3'])

0 1
1 2
2 3


In [59]:
diga_indice(['a', 'b', 'c', 'd', 'e'])

0 a
1 b
2 c
3 d
4 e


## Numpy

O elemento central do numpy são os arrays, então aqui vamos treinar muitas coisas sobre eles

In [60]:
# Importando a biblioteca
import numpy as np

### Arrays

In [61]:
a = np.array([1, 2, 3, 4, 5, 6, 7])

b = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

c = np.zeros((3,4))

In [62]:
# Pense em qual é a shape de cada um dos arrays acima
# Depois de pensar imprima cada um deles para conferir sua resposta
print(a.shape)
print(b.shape)
print(c.shape)

(7,)
(2, 4)
(3, 4)


In [63]:
# Crie um array de uma dimenção com 20 elementos inteiros aletórios entre 0 e 23bb
d = np.random.randint(24, size=(20))
d

array([13,  7,  3,  1, 11,  3, 19,  6, 19,  4,  5, 12, 17,  4, 20,  5, 15,
       21,  8,  9])

In [64]:
# Crie um array de uns com shape (4, 5)
e = np.ones([4, 5])
e

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [65]:
# Crie um array shape (4, 2) onde cada entrada vale 77
# (Dica: Talvez vc tenha que usar uma multiplicação)
f = np.ones([4, 2]) * 77
f

array([[77., 77.],
       [77., 77.],
       [77., 77.],
       [77., 77.]])

In [66]:
# Gere um array chamado my_sequence com os numeros 0, 10, 20, 30, ..., 90, 100]
g = np.arange(101)
g

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

### Indexando

In [67]:
my_array = np.random.randint(50, size=(15,))
print(my_array)

[32 12 41 27  5 42  8  9 41  6 36  0 23 16 31]


In [68]:
# Selecione todos os elementos entre o quinto e o decimo primeiro (intervalo fechado)
my_array[4:11]

array([ 5, 42,  8,  9, 41,  6, 36])

In [69]:
# Selecione todos os elementos maiores que 20
my_array[my_array > 20]

array([32, 41, 27, 42, 41, 36, 23, 31])

In [70]:
my_matrix = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12],
                      [13, 14, 15, 16]])

In [71]:
# Selecione o elemento na primeira linha da terceira coluna
my_matrix[0, 2]

3

In [72]:
# Selecione o elemento na primeira linha da ultima coluna
my_matrix[0, -1]

4

In [73]:
# Selecione os elementos da matriz para obter o seguinte
# [[6, 7],
#  [10, 11]]
my_matrix[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [74]:
# Selecione os elementos da matriz para obter o seguinte
# [[2, 3, 4],
#  [6, 7, 8]]
my_matrix[0:2, 1:4]

array([[2, 3, 4],
       [6, 7, 8]])

In [75]:
# Selecione os elementos da ultima coluna inteira
my_matrix[:, -1]

array([ 4,  8, 12, 16])

In [76]:
# Selecione os elementos da 2a linha inteira
my_matrix[1,:]

array([5, 6, 7, 8])

### Operações

In [77]:
my_array = np.random.randint(10, size=(5,))
print(my_array)

[8 3 1 7 4]


In [78]:
# Some 10 a todos os elementos de my_array
my_array = my_array + 10
my_array

array([18, 13, 11, 17, 14])

In [79]:
# Multiplique todos os elementos de my_array por 4
my_array = my_array * 4
my_array

array([72, 52, 44, 68, 56])

In [80]:
# Obtenha a soma de todos os elementos de my_array
my_array.sum()

292

In [81]:
# Obtenha a média de todos os elementos de my_array
my_array.mean()

58.4

In [82]:
# Obtenha o indice do maior elemento de my_array
np.argmax(my_array)

0

In [83]:
my_array = np.random.randint(10, size=(5,))
my_other_array = np.random.randint(10, size=(5,))
print(my_array, '\n')
print(my_other_array)

[8 2 2 2 4] 

[1 2 2 6 4]


In [84]:
my_array = np.random.randint(10, size=(5,))
my_other_array = np.random.randint(10, size=(10,5))
print(my_array, '\n')
print(my_other_array)

[3 8 3 5 3] 

[[8 0 4 4 9]
 [2 9 0 8 4]
 [9 5 0 7 6]
 [2 9 3 0 5]
 [7 4 4 5 7]
 [8 9 3 6 0]
 [7 9 6 9 9]
 [3 1 5 3 1]
 [4 1 7 4 2]
 [1 5 4 3 0]]


In [85]:
# Some my_array elemento por elemento em cada linha de my_other_array
my_other_array + my_array

array([[11,  8,  7,  9, 12],
       [ 5, 17,  3, 13,  7],
       [12, 13,  3, 12,  9],
       [ 5, 17,  6,  5,  8],
       [10, 12,  7, 10, 10],
       [11, 17,  6, 11,  3],
       [10, 17,  9, 14, 12],
       [ 6,  9,  8,  8,  4],
       [ 7,  9, 10,  9,  5],
       [ 4, 13,  7,  8,  3]])

In [86]:
my_array = np.random.randint(10, size=(5,4))
my_other_array = np.random.randint(10, size=(10,5))
print(my_array, '\n')
print(my_other_array)

[[1 6 4 6]
 [8 1 5 8]
 [1 9 5 6]
 [0 8 4 8]
 [2 9 3 8]] 

[[1 7 9 3 2]
 [8 6 6 6 4]
 [8 8 5 2 8]
 [7 6 1 2 2]
 [8 9 9 6 5]
 [7 1 5 0 8]
 [9 9 6 9 0]
 [6 8 6 8 0]
 [0 7 4 1 4]
 [7 9 0 8 4]]


In [87]:
# Faça a multiplicação entre my_other_array e my_array
np.dot(my_other_array, my_array)

array([[ 70, 136, 102, 156],
       [ 70, 192, 128, 212],
       [ 93, 189, 129, 222],
       [ 60,  91,  77, 128],
       [ 99, 231, 161, 262],
       [ 36, 160,  82, 144],
       [ 87, 189, 147, 234],
       [ 76, 162, 126, 200],
       [ 68,  87,  71, 120],
       [ 87, 151, 117, 210]])

In [88]:
# Descubra a soma dos valores de cada linha de my_other_array
# (Dica: Pesquise sobre o atributo axis da função de soma)
my_other_array.sum(axis=1)

array([22, 30, 31, 18, 37, 21, 33, 28, 16, 28])

In [89]:
my_array = np.random.randint(10, size=(5,4))
print(my_array)

[[8 7 8 7]
 [8 5 8 8]
 [8 9 1 8]
 [5 5 5 0]
 [0 9 3 6]]


In [90]:
# Usando reshape transforme a matriz acima em um vetor (Concatendo a linha de baixo na de cima)
my_array.reshape(-1)

array([8, 7, 8, 7, 8, 5, 8, 8, 8, 9, 1, 8, 5, 5, 5, 0, 0, 9, 3, 6])

In [91]:
np.array([[ 0,  1,  2,  3,  4,  5,  6,  7],
          [ 8,  9, 10, 11, 12, 13, 14, 15]])

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [92]:
# Gere a array anterior usando np.arange e a função reshape
